Cleanup

diff --git a/.github/workflows/homebrew.yml b/.github/workflows/homebrew.yml
--- a/.github/workflows/homebrew.yml
+++ b/.github/workflows/homebrew.yml
@@ -13,10 +13,10 @@ jobs:
 
     steps:
       - name: Check brew
-        run: which brew || echo "Program not found"
+        run: which brew || echo 'Program not found.'
 
       - name: Check fortune
-        run: which fortune || echo "Program not found"
+        run: which fortune || echo 'Program not found.'
 
       - uses: Homebrew/actions/setup-homebrew@master
 
@@ -24,6 +24,4 @@ jobs:
         run: brew install fortune
 
       - name: Run fortune
-        run: |
-          which fortune
-          fortune
+        run: fortune
